export default [
  {
    name: "Shekhar Suman",
    company: "OneShot",
    email: "shekhar.suman@oneshot.ai",
    phone: "8884447813",
    jobTitle: "Software Engineer",
    mailsSent: 3,
    openRate: 13,
  },
  {
    name: "Ram",
    company: "Google",
    email: "ram@google.com",
    phone: "8884447813",
    jobTitle: "Sales Manager",
    mailsSent: 3,
    openRate: 13,
  },
  {
    name: "john",
    company: "Juniper",
    email: "john@juniper.com",
    phone: "8884447813",
    jobTitle: "CEO",
    mailsSent: 5,
    openRate: 22,
  },
  {
    name: "Raghu",
    company: "Cisco",
    email: "raghu.g@cisco.com",
    phone: "8884447813",
    jobTitle: "Sales Rep",
    mailsSent: 1,
    openRate: 10,
  },
  {
    name: "Vinay",
    company: "Adobe",
    email: "vinay@adobe.com",
    phone: "8884447813",
    jobTitle: "Sales Ops",
    mailsSent: 8,
    openRate: 20,
  },
  {
    name: "Pattric",
    company: "OneShot",
    email: "pattric.d@oneshot.ai",
    phone: "8884447813",
    jobTitle: "Software Engineer",
    mailsSent: 2,
    openRate: 5,
  },
  {
    name: "Nitin Jain",
    company: "OneShot",
    email: "shekhar.suman@oneshot.ai",
    phone: "8884447813",
    jobTitle: "Software Engineer",
    mailsSent: 5,
    openRate: 19,
  },
  {
    name: "Subham Raj",
    company: "OneShot",
    email: "shekhar.suman@oneshot.ai",
    phone: "8884447813",
    jobTitle: "Software Engineer",
    mailsSent: 6,
    openRate: 10,
  },
  {
    name: "Sonali",
    company: "OneShot",
    email: "shekhar.suman@oneshot.ai",
    phone: "8884447813",
    jobTitle: "Software Engineer",
    mailsSent: 4,
    openRate: 12,
  },
  {
    name: "Aakansha Aditi",
    company: "OneShot",
    email: "shekhar.suman@oneshot.ai",
    phone: "8884447813",
    jobTitle: "Software Engineer",
    mailsSent: 2,
    openRate: 10,
  },
  {
    name: "Shekhar Suman",
    company: "OneShot",
    email: "shekhar.suman@oneshot.ai",
    phone: "8884447813",
    jobTitle: "Software Engineer",
    mailsSent: 1,
    openRate: 5,
  },
  {
    name: "Shekhar Suman",
    company: "OneShot",
    email: "shekhar.suman@oneshot.ai",
    phone: "8884447813",
    jobTitle: "Software Engineer",
    mailsSent: 3,
    openRate: 14,
  },
  {
    name: "Shekhar Suman",
    company: "OneShot",
    email: "shekhar.suman@oneshot.ai",
    phone: "8884447813",
    jobTitle: "Software Engineer",
    mailsSent: 4,
    openRate: 20,
  },
];
